apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web
  namespace: default
  labels:
    app: demo-web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-web
  template:
    metadata:
      labels:
        app: demo-web
    spec:
      containers:
      - name: web
        image: ligum/demo-app:f9d9e7c4538f28c9d05bdf55d77dccb011670c78
        ports:
        - containerPort: 80
