apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web
  namespace: default
  labels:
    app: demo-web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-web
  template:
    metadata:
      labels:
        app: demo-web
    spec:
      containers:
      - name: web
        image: nginxdemos/hello
        ports:
        - containerPort: 80
